name: Build & Deploy Dotnet app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOTNET_WEBAPI_PATH: './dotnet-webapi-demo'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.DOTNET_WEBAPI_PATH}}/dotnet-webapi-demo.csproj
    - name: Build
      run: dotnet build --no-restore ${{env.DOTNET_WEBAPI_PATH}}/dotnet-webapi-demo.csproj
